### ISSUE TITLE
Incorrect example for ⎕IO=1 on page /SystemFunctions.html

### ISSUE THREAD

**Issue by AleBeda** [xpqz/cultivations#5]
This example does not look correct. The second result should be `1 2 3 4`. The reason is that the assignment of ⎕IO should *precede* `⍳4`.
```
⍳4
⎕IO←0
⍳4
⎕IO←1
0 1 2 3
0 1 2 3
```

**Comment by NaincyKumariKnoldus** [comment]
Hey @AleBeda I would love to do this. Can I?

**Comment by AleBeda** [comment]
@NaincyKumariKnoldus, the repository is not mine. It's up to @xpqz to decide. He probably won't mind if you send him a PR.

**Comment by NaincyKumariKnoldus** [comment]
okay @AleBeda sure I am doing it.

**Comment by NaincyKumariKnoldus** [comment]
Hey @xpqz and @AleBeda I have raised PR for this. Please review this.
Thanks!

**Comment by xpqz** [comment]
Hi @NaincyKumariKnoldus annd @AleBeda -- and thanks for taking the time.

 It's in fact the _first_ result that's wrong; I was relying on ⎕IO being defaulted to 1 when you open a new session in a notebook, but the build system that makes the book has an IO-setting that 'spills over' from an earlier chapter. The last `⎕IO←1` in the section you highlight is simply to return to the default. I'll make it clearer.

For future reference, the HTML pages are auto-generated from the Jupyter notebooks that make up the source for the book; thus any PRs would need to target those, as any changes to the HTML pages will get overwritten next time I run `jupyter-book build`. See https://jupyterbook.org/basics/build.html for details on how that works.

**Comment by NaincyKumariKnoldus** [comment]
Okay! @xpqz You mean to say I have to change first result not second result. Right?

**Comment by xpqz** [comment]
That was my intention, but it works doing it like so, which should be immune to this problem:

```apl
⍳4 ⊣ ⎕IO←0
⍳4 ⊣ ⎕IO←1
```

**Comment by NaincyKumariKnoldus** [comment]
okay I am changing first result. Correct?

**Comment by xpqz** [comment]
I've fixed it already this time. But as I said, your PR would have needed to target the notebook itself

Fixed in 142e6af3877ddfb67f4e24ef53d7de4aab93c8bd

**Comment by NaincyKumariKnoldus** [comment]
Means ......I havent understand.

**Comment by xpqz** [comment]
So assuming you're not familiar with jupyter and jupyter-book....the book is built from jupyter notebooks and the Dyalog jupyter kernel. The website's html is automatically generated, and need never be modified manually. 

The notebook in question is this: 

    https://github.com/xpqz/cultivations/blob/main/contents/SystemFunctions.ipynb

Any changes to the book's content text, code examples etc always go in the notebook files (`contents/*.ipynb`). The `_build/html/*.html` files are build artefacts only -- they're generated by the `jupyter-book build contents` command. 

Whilst the notebooks themselves are basically just a bunch of json, they're not intended to be edited directly. Instead, in order to make changes to the notebooks you need the following bits and bobs installed:

1. Jupyter itself (https://jupyter.org/)
2. the Dyalog jupyter kernel (https://github.com/Dyalog/dyalog-jupyter-kernel)
3. the jupyter-book authoring system (https://jupyterbook.org)

With that in place, you can edit directly in a web browser, crucially including executing APL code in place.

Your PR changes the build artefacts, not the source. Instead, had you changed the notebook source, the build process would have executed the APL snippet, and included the (correct) output into the generated html.

Don't let this put you off: you spotted a problem, reported it, and it got fixed. Play around a bit with the jupyterbook system; it's a super-cool tool chain to do this kind of thing with.
